---

- name: Install ntp and ntpdate
  apt: pkg={{ item }} state=installed update_cache=false
  with_items:
    - ntp
    - ntpdate

- name: Start Ntp server
  service: name=ntp state=started

- name: Delete all ntp source servers
  lineinfile: backup=yes dest=/etc/ntp.conf state=absent regexp=^server

- name: Add Controller as the ntp source server
  lineinfile: dest=/etc/ntp.conf state=present line={{ item }}
  with_items:
    - "# Controller ntp server"
    - "server {{ controller_ip }}"
  
- name: Restart Ntp server
  service: name=ntp state=restarted

