---

- name: Stop the service
  service: name=openbach-agent state=stopped
    
- name: Remove the service
  file: path=/etc/init.d/openbach-agent state=absent
  
- name: Uninstall the daemon
  file: path=/opt/openbach-agent/ state=absent
    
- name: Remove openbach pid repository
  file: path=/var/run/openbach state=absent
  
- name: Remove Jobs' sources
  file: path=/opt/openbach-jobs/ state=absent

- name: Remove python-apscheduler
  pip: name=apscheduler state=absent executable=pip3

- name: Remove python3-pip
  apt: pkg=python3-pip state=absent update_cache=false
  
