# 
#   OpenBACH is a generic testbed able to control/configure multiple
#   network/physical entities (under test) and collect data from them. It is
#   composed of an Auditorium (HMIs), a Controller, a Collector and multiple
#   Agents (one for each network entity that wants to be tested).
#   
#   
#   Copyright © 2016 CNES
#   
#   
#   This file is part of the OpenBACH testbed.
#   
#   
#   OpenBACH is a free software : you can redistribute it and/or modify it under the
#   terms of the GNU General Public License as published by the Free Software
#   Foundation, either version 3 of the License, or (at your option) any later
#   version.
#   
#   This program is distributed in the hope that it will be useful, but WITHOUT
#   ANY WARRANTY, without even the implied warranty of MERCHANTABILITY or FITNESS
#   FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
#   details.
#   
#   You should have received a copy of the GNU General Public License along with
#   this program. If not, see http://www.gnu.org/licenses/.
#   
#   
#   
#   @file     uninstall_daemon.yml
#   @brief    Tasks that uninstall the Control-Agent
#   @author   Adrien THIBAUD <adrien.thibaud@toulouse.viveris.com>


---

- name: Stop the service
  service: name=openbach-agent state=stopped
    
- name: Remove the service
  file: path=/etc/init.d/openbach-agent state=absent
  
- name: Uninstall the daemon
  file: path=/opt/openbach-agent/ state=absent
    
- name: Remove openbach pid repository
  file: path=/var/run/openbach state=absent
  
- name: Remove Jobs' sources
  file: path=/opt/openbach-jobs/ state=absent

- name: Remove python-apscheduler
  pip: name=apscheduler state=absent executable=pip3

- name: Remove python3-pip
  apt: pkg=python3-pip state=absent update_cache=false
  
