---

- hosts: Agents
  remote_user: root
  vars_files:
    - vars/main.yml
  vars:
    - id: 1
    - date_interval_stop: date now

  tasks:
    - include: ../../../roles/backend/tasks/status_job.yml

