---

- hosts: Agents
  vars_files:
    - vars/main.yml
  vars:
    - job_conf: cwnd_monitoring.cfg

  tasks:
  - name: Uninstall Cwnd Monitoring
    file: path=/opt/openbach-jobs/cwnd_monitoring state=absent
    become: yes

  - name: Inform Agent that Cwnd Monitoring is uninstalled
    file: path=/opt/openbach-agent/jobs/{{ job_conf }} state=absent
    become: yes

  - include: '{{ path_src }}/del_job.yml'

