---

- hosts: Agents
  vars_files:
    - vars/main.yml

  tasks:
  - name: Uninstall Ping Job
    file: path=/opt/openbach-jobs/ping state=absent
    become: yes
    
  - name: Informe Agent that Ping is uninstalled
    file: path=/opt/openbach-agent/jobs/{{ job_name }}.cfg state=absent
    become: yes
    
  - include: /opt/openbach/roles/backend/tasks/remove_job.yml
  
