---

- hosts: Agents
  remote_user: root
  vars_files:
    - vars/main.yml
  vars:
    - job_conf: ping.cfg

  tasks:
  - name: Inform Agent that Ping is uninstalled
    file: path=/opt/openbach-agent/jobs/{{ job_conf }} state=absent

  - include: ../../../../roles/backend/tasks/remove_job.yml

