---

- hosts: Agents
  roles:
    - agents
  remote_user: root

  tasks:
  - name: Install Rstats
    copy: src=roles/agents/templates/rstats/ dest=/opt/rstats/ mode=0644

  - name: Configure Rstats
    template: src=roles/agents/templates/rstats.cfg.j2 dest=/opt/rstats/rstats.cfg

  - name: Create Rstats Service
    copy: src=roles/agents/templates/rstats_service dest=/etc/init.d/rstats mode=0755

  - name: Start Rstats
    service: name=rstats state=started

- hosts: Collector
  roles:
    - collector
  remote_user: root
  vars:
    - influxdb_version: 0.10.0-1

  tasks:
  - name: Download InfluxDB (64bits)
    get_url: url=https://s3.amazonaws.com/influxdb/influxdb_{{ influxdb_version }}_amd64.deb \
      dest=/tmp/ force=no
      
  - name: Install InfluxDB (64bits)
    shell: dpkg -i /tmp/influxdb_{{ influxdb_version }}_amd64.deb
    
  - name: Start InfluxDB
    service: name=influxdb state=started
    
  - name: Wait a little
    shell: sleep 2
    
  - name: Database Creation
    shell: curl -G http://localhost:{{ influxdb_port }}/query --data-urlencode "q={{ item }}"
    with_items:
      - CREATE DATABASE "{{ database_name }}"
      - CREATE USER "{{username}}" WITH PASSWORD '{{ password }}' WITH ALL PRIVILEGES
      
- hosts: Controller
  roles:
    - controller
  remote_user: root

  tasks:
  - name: Add the apt repository
    copy: src=roles/controller/templates/grafana-trusty.list dest=/etc/apt/sources.list.d/
    
  - name: Add the Package Cloud key
    apt_key: url=https://packagecloud.io/gpg.key state=present
    
  - name: Install Grafana
    apt: pkg=grafana state=installed update_cache=true
    
  - name: Configure Grafana
    copy: src=roles/controller/templates/grafana.ini dest=/etc/grafana/ mode=0640
    
  - name: Start Grafana
    service: name=grafana-server state=started

