---

- hosts: Agents
  remote_user: root
  vars_files:
    - vars/main.yml
  vars:
    - job_conf: cwnd_monitoring.cfg

  tasks:
  - name: Create Cwnd Monitoring repository
    file: path=/opt/openbach-plugins/cwnd_monitoring state=directory mode=0755

  - name: Install Cwnd Monitoring
    copy: src=templates/{{ item }} dest=/opt/openbach-plugins/cwnd_monitoring/ mode=0644
    with_items:
      - cwnd.py
      - cwnd_rstats_filter.conf
      - tcp_probe_new_fix.ko
      
  - name: Inform Agent that Cwnd Monitoring is installed
    copy: src=templates/{{ job_conf }} dest=/opt/openbach-agent/jobs/ mode=0644

  - include: ../../../roles/agents/tasks/add_job.yml

