---

- hosts: Agents
  remote_user: root

  tasks:
  - name: Create Cwnd Monitoring repository
    file: path=/opt/openbach-plugins/cwnd_monitoring state=directory mode=0755

  - name: Install Cwnd Monitoring
    copy: src=templates/{{ item }} dest=/opt/openbach-plugins/cwnd_monitoring/ mode=0644
    with_items:
      - cwnd.py
      - cwnd_rstats_filter.conf
      - tcp_probe_new_fix.ko

  - name: Create Cwnd Monitoring Service
    copy: src=templates/cwnd_monitoring dest=/etc/init.d/ mode=0755

