---

- hosts: Agents
  remote_user: root
  vars_files:
    - vars/main.yml
  vars:
    - job_conf: tcp_buffer.cfg

  tasks:
  - name: Create Tcp Buffer repository
    file: path=/opt/openbach-plugins/tcp_buffer state=directory mode=0755

  - name: Install Tcp Buffer
    copy: src=templates/tcp_buffer.sh dest=/opt/openbach-plugins/tcp_buffer/ mode=0755
      
  - name: Inform Agent that Tcp Buffer is installed
    copy: src=templates/{{ job_conf }} dest=/opt/openbach-agent/jobs/ mode=0644

  - include: ../../../roles/agents/tasks/add_job.yml

