# 
#   OpenBACH is a generic testbed able to control/configure multiple
#   network/physical entities (under test) and collect data from them. It is
#   composed of an Auditorium (HMIs), a Controller, a Collector and multiple
#   Agents (one for each network entity that wants to be tested).
#   
#   
#   Copyright © 2016 CNES
#   
#   
#   This file is part of the OpenBACH testbed.
#   
#   
#   OpenBACH is a free software : you can redistribute it and/or modify it under the
#   terms of the GNU General Public License as published by the Free Software
#   Foundation, either version 3 of the License, or (at your option) any later
#   version.
#   
#   This program is distributed in the hope that it will be useful, but WITHOUT
#   ANY WARRANTY, without even the implied warranty of MERCHANTABILITY or FITNESS
#   FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
#   details.
#   
#   You should have received a copy of the GNU General Public License along with
#   this program. If not, see http://www.gnu.org/licenses/.
#   
#   
#   
#   @file     main.yml
#   @brief    File that containts all the variable needed for the playbooks
#   @author   Adrien THIBAUD <adrien.thibaud@toulouse.viveris.com>


---

- hosts: Agents
  vars_files:
    - vars/main.yml
  vars:
    - job_conf: post_processing_tcp_pep.cfg
  
  tasks:
  - name: Create Tcp Pep repository
    file: path=/opt/openbach-jobs/{{ job_name }} state=directory mode=0755
    become: yes

  - name: Install Tcp Pep
    copy: src=files/{{ item }} dest=/opt/openbach-jobs/{{  job_name }}/ mode=0644
    with_items:
      - "{{ job_name }}.py"
      - "{{ job_name }}.help"
      - "{{ job_name }}_rstats_filter.conf"
    become: yes
    
  - name: Install Tcp pep configuration file
    copy: src=files/{{ job_conf }} dest=/opt/openbach-agent/jobs/ mode=0644
    become: yes
    
  - include: '{{ path_src }}/add_job.yml'

