---

- hosts: Agents
  remote_user: root
  vars_files:
    - vars/main.yml

  tasks:
  - name: Uninstall Rate Monitoring
    file: path=/opt/openbach-plugins/rate_monitoring/rate{{ item }} state=absent
    with_items:
      - .py
      - _rstats_filter.conf
      - _monitoring.cfg

  - name: Remove Rate Monitoring repository
    file: path=/opt/openbach-plugins/rate_monitoring state=absent

  - include: ../../../roles/agents/tasks/remove_job.yml

