# 
#   OpenBACH is a generic testbed able to control/configure multiple
#   network/physical entities (under test) and collect data from them. It is
#   composed of an Auditorium (HMIs), a Controller, a Collector and multiple
#   Agents (one for each network entity that wants to be tested).
#   
#   
#   Copyright © 2016 CNES
#   
#   
#   This file is part of the OpenBACH testbed.
#   
#   
#   OpenBACH is a free software : you can redistribute it and/or modify it under the
#   terms of the GNU General Public License as published by the Free Software
#   Foundation, either version 3 of the License, or (at your option) any later
#   version.
#   
#   This program is distributed in the hope that it will be useful, but WITHOUT
#   ANY WARRANTY, without even the implied warranty of MERCHANTABILITY or FITNESS
#   FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
#   details.
#   
#   You should have received a copy of the GNU General Public License along with
#   this program. If not, see http://www.gnu.org/licenses/.
#   
#   
#   
#   @file     agent.yml
#   @brief    Playbook that install an Agent
#   @author   Adrien THIBAUD <adrien.thibaud@toulouse.viveris.com>


---

- hosts: localhost
  connection: local

  tasks:
    - name: Make sure the known hosts file exists
      file: path=/etc/ssh/ssh_known_hosts state=touch
      tags:
        - install
        - uninstall

    - name: Check host name availability
      shell: ssh-keygen -f /etc/ssh/ssh_known_hosts -F {{ item }}
      with_items: '{{agents}}'
      register: ssh_known_host_results
      ignore_errors: yes
      tags:
        - install
        - uninstall

    - name: Scan Controller public key
      shell: ssh-keyscan -H -T 10 {{ item.item }} >> /etc/ssh/ssh_known_hosts
      with_items: '{{ssh_known_host_results.results}}'
      when: item.stdout == ""
      tags:
        - install
        - uninstall

- hosts: Agents 
  roles:
    - agent
  become: yes

