#!/bin/bash

if [ -z $1 ]
then
    msg="Usage: $0 dest [options ...]"
    echo $msg
    logger -t $(basename $0) $msg
    exit 1
fi
dest=$1
shift
options=$@

ping $dest $options | logger -t $(basename $0) 
[ "$?" != "0" ] &&  logger -t $(basename $0) "Error" || :

