#!/bin/bash
# This script is used by the OpenBACH conductor (Controller) to give his order to the Agent

if [ -z "$1" ]
then
    echo "Usage 1: $0 {add_job_agent|del_job_agent} *job_name*"
    echo "Usage 2: $0 {start_job_instance_agent|restart_job_instance_agent} *job_name* *instance_id* {date *date*|interval *interval} [options]"
    echo "Usage 3: $0 status_job_instance_agent *job_name* *instance_id* {date *date*|interval *interval|stop}"
    echo "Usage 4: $0 stop_job_instance_agent *job_name* *instance_id* date *date*"
    echo "Usage 5: $0 status_jobs_agent"
    exit 1
fi

if [ $1 != "status_jobs_agent" ]
then
    if [ -z "$2" ]
    then
        echo "Usage 1: $0 {add_job_agent|del_job_agent} *job_name*"
        echo "Usage 2: $0 {start_job_instance_agent|restart_job_instance_agent} *job_name* *instance_id* {date *date*|interval *interval} [options]"
        echo "Usage 3: $0 status_job_instance_agent *job_name* *instance_id* {date *date*|interval *interval|stop}"
        echo "Usage 4: $0 stop_job_instance_agent *job_name* *instance_id* date *date*"
        echo "Usage 5: $0 status_jobs_agent"
        exit 1
    fi
fi

result=`echo "$@" | nc localhost 1112`

IFS=' ' read -ra arr <<< "$result"
if [ $arr = "OK" ]; then
    echo $result
    exit 0
elif [ $arr = "KO" ]; then
    echo $result
    exit 2
else
    echo $result
    exit 3
fi

