#!/bin/bash
# status-manager daemon
# description: status-manager daemon
# processname: status-manager

DAEMON_PATH="/opt/openbach-controller/status-manager/"

DAEMON=./status-manager.py
DAEMONOPTS=""

NAME=status-manager
DESC="My daemon description"
PIDFILE=/var/run/$NAME.pid

case "$1" in
start)
    printf "%-50s" "Starting $NAME..."
    cd $DAEMON_PATH
    PID=`$DAEMON $DAEMONOPTS > /dev/null 2>&1 & echo $!`
    if [ -z $PID ]; then
        printf "%s\n" "Fail"
    else
        echo $PID > $PIDFILE
        printf "%s\n" "Ok"
    fi
;;
status)
    printf "%-50s" "Checking $NAME ..."
    error=0
    if [ -f $PIDFILE ]; then
        PID=`cat $PIDFILE`
        if [ -z "`ps axf | grep ${PID} | grep -v grep`" ]; then
            printf "%s\n" "Process dead but pidfile exists"
            error=1
        else
            echo "Running"
        fi
    else
        printf "%s\n" "Service not running"
        error=2
    fi
    exit $error
;;
stop)
    printf "%-50s" "Stopping $NAME"
    if [ -f $PIDFILE ]; then
        PID=`cat $PIDFILE`
        kill -TERM $PID
        printf "%s\n" "Ok"
        rm -f $PIDFILE
    else
        printf "%s\n" "pidfile not found"
    fi
;;
restart)
    $0 stop
    $0 start
;;

*)
    echo "Usage: $0 {status|start|stop|restart}"
    exit 1
esac
