---

- name: restart elasticsearch
  systemd: name=elasticsearch state=restarted enabled=yes daemon_reload=yes
  become: yes

- name: restart logstash
  systemd: name=logstash state=restarted enabled=yes daemon_reload=yes
  become: yes

- name: restart influxdb
  systemd: name=influxdb state=restarted enabled=yes daemon_reload=yes
  become: yes
  notify: wait for influxdb to start

- name: wait for influxdb to start
  wait_for: port={{ influxdb_port }} timeout=10
  notify: create default influxdb database

- name: create default influxdb database
  influxdb_database: hostname=localhost database_name={{ influxdb_database_name }} state=present
  become: yes
