---

- name: restart elasticsearch
  systemd: name=elasticsearch state=restarted enabled=yes daemon_reload=yes
  become: yes

- name: restart logstash
  systemd: name=logstash state=restarted enabled=yes daemon_reload=yes
  become: yes

- name: restart influxdb
  systemd: name=influxdb state=restarted enabled=yes daemon_reload=yes
  become: yes
