---

- hosts: Agents
  vars_files:
    - vars/main.yml
  vars:
    - job_conf: initial_windows.cfg

  tasks:
  - name: Create Initial Windows repository
    file: path=/opt/openbach-jobs/initial_windows state=directory mode=0755
    become: yes

  - name: Install Initial Windows
    copy: src=files/initial_windows.sh dest=/opt/openbach-jobs/initial_windows/ mode=0755
    become: yes
      
  - name: Inform Agent that Initial Windows is installed
    copy: src=files/{{ job_conf }} dest=/opt/openbach-agent/jobs/ mode=0644
    become: yes

  - include: ../../../roles/backend/tasks/add_job.yml

