---

- hosts: Controller
  roles:
    - controller
  remote_user: root
  vars:
   - version_kibana: 4.3.1
   - controller_archi: x64
  
  tasks:
  # Ansible Part
  - name: Add Ansible repository
    apt_repository: repo=ppa:ansible/ansible update_cache=yes
    
  - name: Install software-properties-common
    apt: pkg=software-properties-common update_cache=false
    
  - name:  Install Ansible
    apt: pkg=ansible update_cache=false
  

  # Synchro part
  - name: Install ntp and ntpdate
    apt: pkg={{ item }} state=installed update_cache=false
    with_items:
      - ntp
      - ntpdate
      
  - name: Start Ntp server
    service: name=ntp state=started

  # Log part
  - name: Download and Uncompress Kibana
    unarchive: src=https://download.elastic.co/kibana/kibana/kibana-{{ version_kibana }}-linux-{{ controller_archi }}.tar.gz \
      dest=/tmp/ copy=no
      
  - name: Create Kibana repository
    file: path=/opt/kibana state=directory mode=0755
    
  - name: Install Kibana
    shell: cp -R /tmp/kibana-{{ version_kibana }}-linux-{{ controller_archi }}/* /opt/kibana
    
  - name: Configure Kibana
    template: src=roles/controller/templates/kibana.yml.j2 dest=/opt/kibana/config/kibana.yml \
      owner=root group=root

  - name: Create Kibana Service
    copy: src=roles/controller/templates/kibana dest=/etc/init.d/ mode=0755
    
  - name: Start Kibana
    service: name=kibana state=started
    
  # Stats part
  - name: Add the apt repository
    copy: src=roles/controller/templates/grafana-trusty.list dest=/etc/apt/sources.list.d/
    
  - name: Add the Package Cloud key
    apt_key: url=https://packagecloud.io/gpg.key state=present
    
  - name: Install Grafana
    apt: pkg=grafana state=installed update_cache=true
    
  - name: Configure Grafana
    copy: src=roles/controller/templates/grafana.ini dest=/etc/grafana/ mode=0640

  - name: Start Grafana
    service: name=grafana-server state=started

