---

- name: restart postgresql
  systemd: name=postgresql state=restarted enabled=yes daemon_reload=yes
  become: yes

- name: restart rsyslog
  systemd: name=rsyslog state=restarted enabled=yes daemon_reload=yes
  become: yes

- name: restart pgbouncer
  systemd: name=pgbouncer state=restarted enabled=yes daemon_reload=yes
  become: yes
