#!/bin/bash
# Ce script est utilisé par le controlleur d'OpenBACH pour communiquer et donner ses ordres à l'agent

if [ -z "$2" ]
then
    echo "Usage 1: $0 {install|uninstall} *job_name*"
    echo "Usage 2: $0 {start|restart} *job_name* *id* {date *date*|interval *interval} [options]"
    echo "Usage 3: $0 status *job_name* *id* {date *date*|interval *interval|stop}"
    echo "Usage 4: $0 {start|status|stop|restart} *job_name* *id* date *date*"
    echo "Usage 5: $0 ls"
    exit 1
fi

if [ $1 != "ls" ]
then
    if [ -z "$2" ]
    then
        echo "Usage 1: $0 {install|uninstall} *job_name*"
        echo "Usage 2: $0 {start|restart} *job_name* *id* {date *date*|interval *interval} [options]"
        echo "Usage 3: $0 status *job_name* *id* {date *date*|interval *interval|stop}"
        echo "Usage 4: $0 {start|status|stop|restart} *job_name* *id* date *date*"
        echo "Usage 5: $0 ls"
        exit 1
    fi
fi

result=`echo "$@" | nc localhost 1112`

IFS=' ' read -ra arr <<< "$result"
if [ $arr = "OK" ]; then
    exit 0
elif [ $arr = "KO" ]; then
    echo $result
    exit 2
else
    echo $result
    exit 3
fi

