---

- name: Create openbach User
  user: name=openbach shell=/bin/bash
  become: yes

- name: Trust the install SSH key by the openbach user
  authorized_key: user=openbach key={{ lookup('file', '{{ ansible_ssh_private_key_file }}.pub') }}
  become: yes

- name: Create openbach folder in /opt
  file: path=/opt/openbach owner=openbach group=openbach state=directory
  become: yes

- name: Add OpenBACH repository
  apt_repository: repo={{ openbach_repository }} state=present update_cache=yes
  become: yes
  environment: "{{ openbach_proxy_env }}"
