---

general:
  name:            configure_link
  description: >
      This Job configures the delay and bandwidth on an interface (it removes the previous configuration of the interface)

  job_version:     '1.0'
  keywords:        [delay, bandwidth, interface, link, netem]
  persistent:      False
  need_privileges: True

platform_configuration:
  - ansible_system: 'Linux'
    ansible_distribution: 'Ubuntu'
    ansible_distribution_version: '16.04'
    command: '/usr/bin/env python3 /opt/openbach/agent/jobs/configure_link/configure_link.py'
    command_stop:

arguments:
  required:
    - name:        interface_name
      type:        'str'
      count:       1
      description: >
          The name of the interface, or multiple separated by commas

  optional:
    - name:        delay
      type:        'int'
      count:       1
      flag:        '-d'
      description: >
          The delay to add, in milliseconds (default=0)

    - name:        loss
      type:        'int'
      count:       1
      flag:        '-l'
      description: >
          The loss to add, in percentage (default=0)

    - name:        bandwidth
      type:        'str'
      count:       1
      flag:        '-b'
      description: >
          The maximum bandwidth. Accepted units are (M)bps and (K)bps (default=no limit).
   
statistics:
