---

general:
  name:            ifconfig
  description: >
      This Job assignes an IP address to an agent's interface

  job_version:     0.1
  keywords:        [ifconfig]
  persistent:      false

os:
  linux:
    requirements:  'Ubuntu 14.04/16.04'
    command:       '/usr/bin/env python3 /opt/openbach-jobs/ifconfig/ifconfig.py'
    command_stop:

arguments:
  required:
    - name:        interface_name
      type:        'str'
      count:       1
      description: >
          The name of the interface

  optional:
    - name:        ip_address
      type:        'ip'
      count:       1
      flag:        '-i'
      description: >
          The ip address to assign to the interface

    - name:        action
      type:        'int'
      count:       1
      flag:        '-a'
      description: >
          Add (1) or delete (0) an interface's ip address. Default=1
   
statistics:

