---

- hosts: Agents
  vars_files:
    - vars/main.yml
  vars:
    - job_conf: rstats_job.cfg

  tasks:
  - name: Create Rstats_job repository
    file: path=/opt/openbach-jobs/rstats_job/ state=directory
    become: yes

  - name: Install Rstats_job
    copy: src=files/{{ item.file }} dest=/opt/openbach-jobs/rstats_job/ mode={{ item.mode }}
    with_items:
      - { file: 'rstats_job.sh', mode: '0755' }
      - { file: 'rstats_job.help', mode: '0644' }
    become: yes
    
  - name: Inform Agent that Rstats_job is installed
    copy: src=files/{{ job_conf }} dest=/opt/openbach-agent/jobs/ mode=0644
    become: yes

  - include: /opt/openbach/roles/backend/tasks/add_job.yml

