# 
#   OpenBACH is a generic testbed able to control/configure multiple
#   network/physical entities (under test) and collect data from them. It is
#   composed of an Auditorium (HMIs), a Controller, a Collector and multiple
#   Agents (one for each network entity that wants to be tested).
#   
#   
#   Copyright © 2016 CNES
#   
#   
#   This file is part of the OpenBACH testbed.
#   
#   
#   OpenBACH is a free software : you can redistribute it and/or modify it under the
#   terms of the GNU General Public License as published by the Free Software
#   Foundation, either version 3 of the License, or (at your option) any later
#   version.
#   
#   This program is distributed in the hope that it will be useful, but WITHOUT
#   ANY WARRANTY, without even the implied warranty of MERCHANTABILITY or FITNESS
#   FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
#   details.
#   
#   You should have received a copy of the GNU General Public License along with
#   this program. If not, see http://www.gnu.org/licenses/.
#   
#   
#   
#   @file     install_running.yml
#   @brief    Tasks that install the version file on the Auditorium
#   @author   Adrien THIBAUD <adrien.thibaud@toulouse.viveris.com>


---

- name: Create Auditorium repository
  file: path=/opt/openbach-auditorium/ state=directory

- name: Copy the version file on the Auditorium
  copy: src=../openbach-version dest=/opt/openbach-auditorium/version

- name: Informe that an installation is running
  shell: '(echo -en "\ninstallation: running\ndate: "; date +"%m-%d-%y") >> /opt/openbach-auditorium/version'

