---

# Install
- include: install_synchro.yml
- include: install_logs.yml
- include: install_stats.yml
- include: install_daemon.yml

# Install
- include: uninstall_synchro.yml
- include: uninstall_logs.yml
- include: uninstall_stats.yml
- include: uninstall_daemon.yml

