# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-11 12:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('name', models.CharField(max_length=20, unique=True)),
                ('address', models.GenericIPAddressField(primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, max_length=200, null=True)),
                ('update_status', models.DateTimeField(blank=True, null=True)),
                ('reachable', models.BooleanField()),
                ('update_reachable', models.DateTimeField(blank=True, null=True)),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('collector', models.GenericIPAddressField()),
            ],
        ),
        migrations.CreateModel(
            name='Argument_Value',
            fields=[
                ('argument_value_id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_model', models.CharField(editable=False, max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Installed_Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_status', models.DateTimeField(blank=True, null=True)),
                ('severity', models.IntegerField()),
                ('local_severity', models.IntegerField()),
                ('default_stat_storage', models.BooleanField(default=True)),
                ('default_stat_broadcast', models.BooleanField(default=False)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openbach_django.Agent')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('path', models.FilePathField(allow_files=False, allow_folders=True, path='/opt/openbach-controller/jobs', recursive=True)),
                ('help', models.TextField(blank=True, null=True)),
                ('job_version', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('has_uncertain_required_arg', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Job_Argument_Instance',
            fields=[
                ('argument_instance_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Job_Instance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=200)),
                ('update_status', models.DateTimeField()),
                ('start_date', models.DateTimeField()),
                ('stop_date', models.DateTimeField(blank=True, null=True)),
                ('periodic', models.BooleanField()),
                ('is_stopped', models.BooleanField(default=False)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openbach_django.Installed_Job')),
            ],
        ),
        migrations.CreateModel(
            name='Job_Keyword',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Openbach_Function',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Openbach_Function_Argument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('int', 'Integer'), ('bool', 'Bool'), ('str', 'String'), ('float', 'Float'), ('ip', 'IP'), ('list', 'List'), ('json', 'Json'), ('None', 'None')], default='None', max_length=5)),
                ('count', models.CharField(blank=True, max_length=11, null=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('openbach_function', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openbach_django.Openbach_Function')),
            ],
        ),
        migrations.CreateModel(
            name='Openbach_Function_Instance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openbach_function_instance_id', models.IntegerField()),
                ('status', models.CharField(blank=True, max_length=200, null=True)),
                ('status_date', models.DateTimeField(blank=True, null=True)),
                ('time', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Operand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_model', models.CharField(editable=False, max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Optional_Job_Argument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('int', 'Integer'), ('bool', 'Bool'), ('str', 'String'), ('float', 'Float'), ('ip', 'IP'), ('list', 'List'), ('json', 'Json'), ('None', 'None')], default='None', max_length=5)),
                ('count', models.CharField(blank=True, max_length=11, null=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('flag', models.CharField(max_length=200)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openbach_django.Job')),
            ],
        ),
        migrations.CreateModel(
            name='Required_Job_Argument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('int', 'Integer'), ('bool', 'Bool'), ('str', 'String'), ('float', 'Float'), ('ip', 'IP'), ('list', 'List'), ('json', 'Json'), ('None', 'None')], default='None', max_length=5)),
                ('count', models.CharField(blank=True, max_length=11, null=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('rank', models.IntegerField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openbach_django.Job')),
            ],
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('scenario', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Scenario_Argument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('int', 'Integer'), ('bool', 'Bool'), ('str', 'String'), ('float', 'Float'), ('ip', 'IP'), ('list', 'List'), ('json', 'Json'), ('None', 'None')], default='None', max_length=5)),
                ('count', models.CharField(blank=True, max_length=11, null=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openbach_django.Scenario')),
            ],
        ),
        migrations.CreateModel(
            name='Scenario_Instance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=200, null=True)),
                ('status_date', models.DateTimeField(blank=True, null=True)),
                ('is_stopped', models.BooleanField(default=False)),
                ('openbach_function_instance_master', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='openbach_function_instance_master', to='openbach_django.Openbach_Function_Instance')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openbach_django.Scenario')),
            ],
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('frequency', models.TextField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openbach_django.Job')),
            ],
        ),
        migrations.CreateModel(
            name='Statistic_Instance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage', models.BooleanField(default=True)),
                ('broadcast', models.BooleanField(default=False)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openbach_django.Installed_Job')),
                ('stat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openbach_django.Statistic')),
            ],
        ),
        migrations.CreateModel(
            name='Wait_For_Finished',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_instance_id_waited', models.IntegerField()),
                ('openbach_function_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openbach_django.Openbach_Function_Instance')),
            ],
        ),
        migrations.CreateModel(
            name='Wait_For_Launched',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openbach_function_instance_id_waited', models.IntegerField()),
                ('openbach_function_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openbach_django.Openbach_Function_Instance')),
            ],
        ),
        migrations.CreateModel(
            name='Watch',
            fields=[
                ('job_instance_id', models.IntegerField(primary_key=True, serialize=False)),
                ('interval', models.IntegerField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openbach_django.Installed_Job')),
            ],
        ),
        migrations.CreateModel(
            name='Condition_And',
            fields=[
                ('condition_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='openbach_django.Condition')),
            ],
            options={
                'abstract': False,
            },
            bases=('openbach_django.condition',),
        ),
        migrations.CreateModel(
            name='Condition_Below',
            fields=[
                ('condition_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='openbach_django.Condition')),
            ],
            options={
                'abstract': False,
            },
            bases=('openbach_django.condition',),
        ),
        migrations.CreateModel(
            name='Condition_Below_Or_Equal',
            fields=[
                ('condition_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='openbach_django.Condition')),
            ],
            options={
                'abstract': False,
            },
            bases=('openbach_django.condition',),
        ),
        migrations.CreateModel(
            name='Condition_Equal',
            fields=[
                ('condition_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='openbach_django.Condition')),
            ],
            options={
                'abstract': False,
            },
            bases=('openbach_django.condition',),
        ),
        migrations.CreateModel(
            name='Condition_Not',
            fields=[
                ('condition_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='openbach_django.Condition')),
            ],
            options={
                'abstract': False,
            },
            bases=('openbach_django.condition',),
        ),
        migrations.CreateModel(
            name='Condition_Or',
            fields=[
                ('condition_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='openbach_django.Condition')),
            ],
            options={
                'abstract': False,
            },
            bases=('openbach_django.condition',),
        ),
        migrations.CreateModel(
            name='Condition_Unequal',
            fields=[
                ('condition_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='openbach_django.Condition')),
            ],
            options={
                'abstract': False,
            },
            bases=('openbach_django.condition',),
        ),
        migrations.CreateModel(
            name='Condition_Upper',
            fields=[
                ('condition_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='openbach_django.Condition')),
            ],
            options={
                'abstract': False,
            },
            bases=('openbach_django.condition',),
        ),
        migrations.CreateModel(
            name='Condition_Upper_Or_Equal',
            fields=[
                ('condition_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='openbach_django.Condition')),
            ],
            options={
                'abstract': False,
            },
            bases=('openbach_django.condition',),
        ),
        migrations.CreateModel(
            name='Condition_Xor',
            fields=[
                ('condition_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='openbach_django.Condition')),
                ('condition1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xor_condition1', to='openbach_django.Condition')),
                ('condition2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xor_condition2', to='openbach_django.Condition')),
            ],
            options={
                'abstract': False,
            },
            bases=('openbach_django.condition',),
        ),
        migrations.CreateModel(
            name='Job_Argument_Value',
            fields=[
                ('argument_value_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='openbach_django.Argument_Value')),
            ],
            bases=('openbach_django.argument_value',),
        ),
        migrations.CreateModel(
            name='Openbach_Function_Argument_Instance',
            fields=[
                ('argument_value_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='openbach_django.Argument_Value')),
                ('argument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openbach_django.Openbach_Function_Argument')),
            ],
            bases=('openbach_django.argument_value',),
        ),
        migrations.CreateModel(
            name='Operand_Database',
            fields=[
                ('operand_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='openbach_django.Operand')),
                ('name', models.CharField(max_length=20)),
                ('key', models.CharField(max_length=20)),
                ('attribute', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
            bases=('openbach_django.operand',),
        ),
        migrations.CreateModel(
            name='Operand_Statistic',
            fields=[
                ('operand_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='openbach_django.Operand')),
                ('measurmement', models.CharField(max_length=200)),
                ('field', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
            bases=('openbach_django.operand',),
        ),
        migrations.CreateModel(
            name='Operand_Value',
            fields=[
                ('operand_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='openbach_django.Operand')),
                ('value', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
            bases=('openbach_django.operand',),
        ),
        migrations.CreateModel(
            name='Optional_Job_Argument_Instance',
            fields=[
                ('job_argument_instance_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='openbach_django.Job_Argument_Instance')),
                ('argument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openbach_django.Optional_Job_Argument')),
            ],
            bases=('openbach_django.job_argument_instance',),
        ),
        migrations.CreateModel(
            name='Required_Job_Argument_Instance',
            fields=[
                ('job_argument_instance_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='openbach_django.Job_Argument_Instance')),
                ('argument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openbach_django.Required_Job_Argument')),
            ],
            bases=('openbach_django.job_argument_instance',),
        ),
        migrations.CreateModel(
            name='Scenario_Argument_Instance',
            fields=[
                ('argument_value_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='openbach_django.Argument_Value')),
                ('argument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openbach_django.Scenario_Argument')),
                ('scenario_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='openbach_django.Scenario_Instance')),
            ],
            bases=('openbach_django.argument_value',),
        ),
        migrations.AddField(
            model_name='openbach_function_instance',
            name='condition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='openbach_django.Condition'),
        ),
        migrations.AddField(
            model_name='openbach_function_instance',
            name='openbach_function',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openbach_django.Openbach_Function'),
        ),
        migrations.AddField(
            model_name='openbach_function_instance',
            name='scenario_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openbach_django.Scenario_Instance'),
        ),
        migrations.AddField(
            model_name='job_instance',
            name='openbach_function_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='openbach_django.Openbach_Function_Instance'),
        ),
        migrations.AddField(
            model_name='job_instance',
            name='scenario_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='openbach_django.Scenario_Instance'),
        ),
        migrations.AddField(
            model_name='job',
            name='keywords',
            field=models.ManyToManyField(to='openbach_django.Job_Keyword'),
        ),
        migrations.AddField(
            model_name='installed_job',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openbach_django.Job'),
        ),
        migrations.AlterUniqueTogether(
            name='statistic_instance',
            unique_together=set([('stat', 'job')]),
        ),
        migrations.AlterUniqueTogether(
            name='statistic',
            unique_together=set([('name', 'job')]),
        ),
        migrations.AlterUniqueTogether(
            name='scenario_argument',
            unique_together=set([('name', 'scenario')]),
        ),
        migrations.AddField(
            model_name='required_job_argument_instance',
            name='job_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openbach_django.Job_Instance'),
        ),
        migrations.AlterUniqueTogether(
            name='required_job_argument',
            unique_together=set([('name', 'job'), ('rank', 'job')]),
        ),
        migrations.AddField(
            model_name='optional_job_argument_instance',
            name='job_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openbach_django.Job_Instance'),
        ),
        migrations.AlterUniqueTogether(
            name='optional_job_argument',
            unique_together=set([('flag', 'job'), ('name', 'job')]),
        ),
        migrations.AlterUniqueTogether(
            name='openbach_function_instance',
            unique_together=set([('openbach_function_instance_id', 'scenario_instance')]),
        ),
        migrations.AddField(
            model_name='openbach_function_argument_instance',
            name='openbach_function_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openbach_django.Openbach_Function_Instance'),
        ),
        migrations.AlterUniqueTogether(
            name='openbach_function_argument',
            unique_together=set([('name', 'openbach_function')]),
        ),
        migrations.AddField(
            model_name='job_argument_value',
            name='job_argument_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openbach_django.Job_Argument_Instance'),
        ),
        migrations.AlterUniqueTogether(
            name='installed_job',
            unique_together=set([('agent', 'job')]),
        ),
        migrations.AddField(
            model_name='condition_upper_or_equal',
            name='operand1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uoe_operand1', to='openbach_django.Operand'),
        ),
        migrations.AddField(
            model_name='condition_upper_or_equal',
            name='operand2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uoe_operand2', to='openbach_django.Operand'),
        ),
        migrations.AddField(
            model_name='condition_upper',
            name='operand1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upper_operand1', to='openbach_django.Operand'),
        ),
        migrations.AddField(
            model_name='condition_upper',
            name='operand2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upper_operand2', to='openbach_django.Operand'),
        ),
        migrations.AddField(
            model_name='condition_unequal',
            name='operand1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unequal_operand1', to='openbach_django.Operand'),
        ),
        migrations.AddField(
            model_name='condition_unequal',
            name='operand2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unequal_operand2', to='openbach_django.Operand'),
        ),
        migrations.AddField(
            model_name='condition_or',
            name='condition1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='or_condition1', to='openbach_django.Condition'),
        ),
        migrations.AddField(
            model_name='condition_or',
            name='condition2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='or_condition2', to='openbach_django.Condition'),
        ),
        migrations.AddField(
            model_name='condition_not',
            name='condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='not_condition', to='openbach_django.Condition'),
        ),
        migrations.AddField(
            model_name='condition_equal',
            name='operand1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equal_operand1', to='openbach_django.Operand'),
        ),
        migrations.AddField(
            model_name='condition_equal',
            name='operand2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equal_operand2', to='openbach_django.Operand'),
        ),
        migrations.AddField(
            model_name='condition_below_or_equal',
            name='operand1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boe_operand1', to='openbach_django.Operand'),
        ),
        migrations.AddField(
            model_name='condition_below_or_equal',
            name='operand2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boe_operand2', to='openbach_django.Operand'),
        ),
        migrations.AddField(
            model_name='condition_below',
            name='operand1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='below_operand1', to='openbach_django.Operand'),
        ),
        migrations.AddField(
            model_name='condition_below',
            name='operand2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='below_operand2', to='openbach_django.Operand'),
        ),
        migrations.AddField(
            model_name='condition_and',
            name='condition1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='and_condition1', to='openbach_django.Condition'),
        ),
        migrations.AddField(
            model_name='condition_and',
            name='condition2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='and_condition2', to='openbach_django.Condition'),
        ),
        migrations.AlterUniqueTogether(
            name='scenario_argument_instance',
            unique_together=set([('argument', 'scenario_instance')]),
        ),
    ]
