# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-07 12:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Action_Argument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('int', 'Integer'), ('bool', 'Bool'), ('str', 'String'), ('float', 'Float'), ('ip', 'IP'), ('list', 'List'), ('None', 'None')], default='None', max_length=5)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openbach_django.Action')),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('name', models.CharField(max_length=20, unique=True)),
                ('address', models.GenericIPAddressField(primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, max_length=200, null=True)),
                ('update_status', models.DateTimeField(blank=True, null=True)),
                ('reachable', models.BooleanField()),
                ('update_reachable', models.DateTimeField(blank=True, null=True)),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('collector', models.GenericIPAddressField()),
            ],
        ),
        migrations.CreateModel(
            name='Argument_Instance',
            fields=[
                ('argument_instance_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Argument_Value',
            fields=[
                ('argument_value_id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Installed_Job',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('update_status', models.DateTimeField(blank=True, null=True)),
                ('severity', models.IntegerField()),
                ('local_severity', models.IntegerField()),
                ('default_stat_storage', models.BooleanField(default=True)),
                ('default_stat_broadcast', models.BooleanField(default=False)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openbach_django.Agent')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('path', models.FilePathField(allow_files=False, allow_folders=True, path='/opt/openbach-controller/jobs', recursive=True)),
                ('help', models.TextField(blank=True, null=True)),
                ('job_version', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job_Instance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=200)),
                ('update_status', models.DateTimeField()),
                ('start_date', models.DateTimeField()),
                ('stop_date', models.DateTimeField(blank=True, null=True)),
                ('periodic', models.BooleanField()),
                ('is_stopped', models.BooleanField(default=False)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openbach_django.Installed_Job')),
            ],
        ),
        migrations.CreateModel(
            name='Job_Keyword',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Optional_Job_Argument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('int', 'Integer'), ('bool', 'Bool'), ('str', 'String'), ('float', 'Float'), ('ip', 'IP'), ('list', 'List'), ('None', 'None')], default='None', max_length=5)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('flag', models.CharField(max_length=200)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openbach_django.Job')),
            ],
        ),
        migrations.CreateModel(
            name='Required_Job_Argument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('int', 'Integer'), ('bool', 'Bool'), ('str', 'String'), ('float', 'Float'), ('ip', 'IP'), ('list', 'List'), ('None', 'None')], default='None', max_length=5)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('rank', models.IntegerField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openbach_django.Job')),
            ],
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('scenario', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Scenario_Argument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('int', 'Integer'), ('bool', 'Bool'), ('str', 'String'), ('float', 'Float'), ('ip', 'IP'), ('list', 'List'), ('None', 'None')], default='None', max_length=5)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openbach_django.Scenario')),
            ],
        ),
        migrations.CreateModel(
            name='Scenario_Instance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openbach_django.Scenario')),
            ],
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('frequency', models.TextField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openbach_django.Job')),
            ],
        ),
        migrations.CreateModel(
            name='Statistic_Instance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage', models.BooleanField(default=True)),
                ('broadcast', models.BooleanField(default=False)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openbach_django.Installed_Job')),
                ('stat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openbach_django.Statistic')),
            ],
        ),
        migrations.CreateModel(
            name='Watch',
            fields=[
                ('instance_id', models.IntegerField(primary_key=True, serialize=False)),
                ('interval', models.IntegerField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openbach_django.Installed_Job')),
            ],
        ),
        migrations.CreateModel(
            name='Job_Argument_Value',
            fields=[
                ('argument_value_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='openbach_django.Argument_Value')),
            ],
            bases=('openbach_django.argument_value',),
        ),
        migrations.CreateModel(
            name='Optional_Job_Argument_Instance',
            fields=[
                ('argument_instance_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='openbach_django.Argument_Instance')),
                ('argument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openbach_django.Optional_Job_Argument')),
                ('job_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openbach_django.Job_Instance')),
            ],
            bases=('openbach_django.argument_instance',),
        ),
        migrations.CreateModel(
            name='Required_Job_Argument_Instance',
            fields=[
                ('argument_instance_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='openbach_django.Argument_Instance')),
                ('argument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openbach_django.Required_Job_Argument')),
                ('job_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openbach_django.Job_Instance')),
            ],
            bases=('openbach_django.argument_instance',),
        ),
        migrations.CreateModel(
            name='Scenario_Argument_Instance',
            fields=[
                ('argument_value_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='openbach_django.Argument_Value')),
                ('argument_instance_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='openbach_django.Argument_Instance')),
                ('argument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openbach_django.Scenario_Argument')),
                ('scenario_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openbach_django.Scenario_Instance')),
            ],
            bases=('openbach_django.argument_instance', 'openbach_django.argument_value'),
        ),
        migrations.AddField(
            model_name='job',
            name='keywords',
            field=models.ManyToManyField(to='openbach_django.Job_Keyword'),
        ),
        migrations.AddField(
            model_name='installed_job',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openbach_django.Job'),
        ),
        migrations.AlterUniqueTogether(
            name='statistic_instance',
            unique_together=set([('stat', 'job')]),
        ),
        migrations.AlterUniqueTogether(
            name='statistic',
            unique_together=set([('name', 'job')]),
        ),
        migrations.AlterUniqueTogether(
            name='scenario_argument',
            unique_together=set([('name', 'scenario')]),
        ),
        migrations.AlterUniqueTogether(
            name='required_job_argument',
            unique_together=set([('name', 'job'), ('rank', 'job')]),
        ),
        migrations.AlterUniqueTogether(
            name='optional_job_argument',
            unique_together=set([('name', 'job'), ('flag', 'job')]),
        ),
        migrations.AddField(
            model_name='job_argument_value',
            name='argument_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openbach_django.Argument_Instance'),
        ),
        migrations.AlterUniqueTogether(
            name='action_argument',
            unique_together=set([('name', 'action')]),
        ),
    ]
