# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-30 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openbach_django', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='password',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='reachable',
            field=models.BooleanField(default=False),
        ),
    ]
