# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-22 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openbach_django', '0002_create_openbach_functions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='openbach_function_instance',
            old_name='status_date',
            new_name='launch_date',
        ),
        migrations.RenameField(
            model_name='scenario_instance',
            old_name='status_date',
            new_name='start_date',
        ),
        migrations.AddField(
            model_name='openbach_function_instance',
            name='label',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='scenario_instance',
            name='stop_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='openbach_function_instance',
            unique_together=set([('label', 'scenario_instance'), ('openbach_function_instance_id', 'scenario_instance')]),
        ),
    ]
