# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-04 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openbach_django', '0002_alter_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installedjob',
            name='local_severity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='installedjob',
            name='severity',
            field=models.IntegerField(default=1),
        ),
    ]
