# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-11 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openbach_django', '0004_alter_passwords_and_auditoriums'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='path',
            field=models.FilePathField(allow_files=False, allow_folders=True, path='/opt/openbach/controller/src/jobs', recursive=True),
        ),
    ]
