# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-02 12:28
from __future__ import unicode_literals

from django.db import migrations
import openbach_django.base_models


class Migration(migrations.Migration):

    dependencies = [
        ('openbach_django', '0006_add_available_field_to_agents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='startjobinstance',
            name='agent_ip',
        ),
        migrations.AddField(
            model_name='startjobinstance',
            name='entity_name',
            field=openbach_django.base_models.OpenbachFunctionArgument(type=str),
        ),
    ]
