# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-06 13:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openbach_django', '0007_start_job_instance_uses_entities'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StopJobInstance',
            new_name='StopJobInstances',
        ),
    ]
