# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-11 07:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openbach_django', '0008_actually_use_stop_job_instances_as_openbach_function'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watch',
            name='job_instance',
        ),
        migrations.RemoveField(
            model_name='watchjobinstance',
            name='openbachfunction_ptr',
        ),
        migrations.DeleteModel(
            name='Watch',
        ),
        migrations.DeleteModel(
            name='WatchJobInstance',
        ),
    ]
