# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-11 15:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openbach_django', '0009_remove_watches'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobinstancecommandresult',
            name='status_watch',
        ),
    ]
