# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-13 13:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('openbach_django', '0010_remove_all_watches'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobinstance',
            name='started_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='private_job_instances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='owners',
            field=models.ManyToManyField(related_name='private_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scenarioinstance',
            name='started_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='private_scenario_instances', to=settings.AUTH_USER_MODEL),
        ),
    ]
