# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-10-23 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openbach_django', '0012_simplify_agent_update'),
    ]

    operations = [
        migrations.RunSQL("DELETE FROM openbach_django_oscommand;"),
        migrations.AddField(
            model_name='oscommand',
            name='distribution',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='oscommand',
            name='family',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='oscommand',
            name='version',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='oscommand',
            unique_together=set([('family', 'distribution', 'version', 'job')]),
        ),
        migrations.RemoveField(
            model_name='oscommand',
            name='requirements',
        ),
        migrations.RemoveField(
            model_name='oscommand',
            name='name',
        ),
    ]
