# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-10-31 10:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openbach_django', '0014_create_scenario_versions'),
    ]

    operations = [
        migrations.CreateModel(
            name='HiddenNetwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hidden_networks', to='openbach_django.Project')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='hiddennetwork',
            unique_together=set([('name', 'project')]),
        ),
    ]
