# -*- coding: utf-
# Generated by Django 1.9.7 on 2017-10-31 15:33
from __future__ import unicode_literals

from django.db import migrations, models


def populate_name_from_address(apps, schema_editor):
    Network = apps.get_model('openbach_django', 'Network')
    for network in Network.objects.all():
        network.name = network.address
        network.save()


class Migration(migrations.Migration):

    dependencies = [
        ('openbach_django', '0015_added_hidden_networks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='network',
            old_name='name',
            new_name='address',
        ),
        migrations.AlterUniqueTogether(
            name='network',
            unique_together=set([('address', 'project')]),
        ),
        migrations.AddField(
            model_name='network',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.RunPython(
            populate_name_from_address,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='network',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
