# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-11-06 14:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openbach_django', '0016_added_network_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='PotentialNetwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='openbach_django.Network')),
                ('old_network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='openbach_django.Network')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='potential_networks', to='openbach_django.Project')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='potentialnetwork',
            unique_together=set([('old_network', 'new_network', 'project')]),
        ),
    ]
