# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-28 10:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def populate_job_instance_infos_from_installed_job(apps, schema_editor):
    JobInstance = apps.get_model('openbach_django', 'JobInstance')
    for job_instance in JobInstance.objects.all():
        job_name = job_instance.job.job.name
        agent = job_instance.job.agent
        job_instance.job_name = job_name
        job_instance.agent_name = agent.name
        job_instance.agent_address = agent.address
        job_instance.collector = agent.collector
        job_instance.save()


def retrieve_installed_job_from_job_instance_infos(apps, schema_editor):
    Job = apps.get_model('openbach_django', 'Job')
    Agent = apps.get_model('openbach_django', 'Agent')
    InstalledJob = apps.get_model('openbach_django', 'InstalledJob')
    JobInstance = apps.get_model('openbach_django', 'JobInstance')

    for job_instance in JobInstance.objects.all():
        try:
            job = Job.objects.get(name=job_instance.job_name)
            agent = Agent.objects.get(address=job_instance.agent_address)
            installed_job = InstalledJob.objects.get(job=job, agent=agent)
            job_instance.job = installed_job
        except (Job.DoesNotExist, Agent.DoesNotExist, InstalledJob.DoesNotExist):
            job_instance.delete()
        else:
            job_instance.save()


class Migration(migrations.Migration):

    dependencies = [
        ('openbach_django', '0018_added_job_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobinstance',
            name='agent_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobinstance',
            name='agent_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='jobinstance',
            name='collector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='openbach_django.Collector'),
        ),
        migrations.AddField(
            model_name='jobinstance',
            name='job_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),

        migrations.RunPython(
            populate_job_instance_infos_from_installed_job,
            reverse_code=retrieve_installed_job_from_job_instance_infos,
        ),

        migrations.RemoveField(
            model_name='jobinstance',
            name='job',
        ),
        migrations.AlterField(
            model_name='jobinstance',
            name='agent_address',
            field=models.GenericIPAddressField(),
        ),
        migrations.AlterField(
            model_name='jobinstance',
            name='agent_name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='jobinstance',
            name='collector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='openbach_django.Collector'),
        ),
        migrations.AlterField(
            model_name='jobinstance',
            name='job_name',
            field=models.CharField(max_length=500),
        ),
    ]
