# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-11 16:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openbach_django', '0019_job_instances_independent_from_agent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentcommandresult',
            name='status_retrieve_status_jobs',
        ),
        migrations.AddField(
            model_name='agentcommandresult',
            name='status_log_severity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='openbach_django.CommandResult'),
        ),
    ]
