#!/bin/bash
# rate monitoring daemon
# description: rate monitoring daemon
# processname: rate monitoring

DAEMON_PATH="/opt/openbach-plugins/rate_monitoring/"

DAEMON=./rate.py

NAME=rate
DESC="My daemon description"
PIDFILE=/var/run/$NAME.pid
SCRIPTNAME=/etc/init.d/$NAME_monitoring

if [ $1 == start ] || [ $1 == restart ]
then
    if [ -z "$2" ]
    then
        echo "Usage: $0 {status|start chain_name matches|stop|restart chain_name matches}"
        echo "Example: $0 start INPUT -p icmp -s 192.168.1.2"
        exit 1
    fi
fi

DO=$1
shift
DAEMONOPTS=$@

case "$DO" in
start)
    printf "%-50s" "Starting $NAME..."
    cd $DAEMON_PATH
    PID=`python $DAEMON $DAEMONOPTS > /dev/null 2>&1 & echo $!`
    #echo "Saving PID" $PID " to " $PIDFILE
    if [ -z $PID ]; then
        printf "%s\n" "Fail"
    else
        echo $PID > $PIDFILE
        printf "%s\n" "Ok"
    fi
;;
status)
    printf "%-50s" "Checking $NAME..."
    if [ -f $PIDFILE ]; then
        PID=`cat $PIDFILE`
        if [ -z "`ps axf | grep ${PID} | grep -v grep`" ]; then
            printf "%s\n" "Process dead but pidfile exists"
        else
            echo "Running"
        fi
    else
        printf "%s\n" "Service not running"
    fi
;;
stop)
    printf "%-50s" "Stopping $NAME"
    PID=`cat $PIDFILE`
    cd $DAEMON_PATH
    if [ -f $PIDFILE ]; then
        kill -HUP $PID
        printf "%s\n" "Ok"
        rm -f $PIDFILE
    else
        printf "%s\n" "pidfile not found"
        exit 1
    fi
;;
restart)
    $0 stop
    $0 start $DAEMONOPTS
;;

*)
    echo "Usage: $0 {status|start chain_name matches|stop|restart chain_name matches}"
    echo "Example: $0 start INPUT -p icmp -s 192.168.1.2"
    exit 1
esac
