---

- hosts: Auditorium
  tasks:
    - name: Add the list of global variables
      copy: src=../configs/{{ item }} dest=/tmp/openbach_{{ item }}
      with_items:
        - all
        - ips
      tags:
        - add_agent

    - name: Add an Agent
      shell: python /opt/openbach-auditorium/frontend_scripts/install_agent.py {{ item.ip }} {{ collector_ip }} {{ agent_username }} {{ agent_password }} {{item.name}}
      with_items: '{{agents}}'
      tags:
        - add_agent

    - name: Del an Agent
      shell: python /opt/openbach-auditorium/frontend_scripts/uninstall_agent.py {{ item }}
      with_items: '{{agents}}'
      tags:
        - del_agent

