---

- hosts: Controller

  tasks:
    - name: Add the list of global variables
      copy: src=../configs/{{ item }} dest=/tmp/openbach_{{ item }}
      with_items:
        - all
        - ips
      tags:
        - add_agent

    - name: Add an Agent
      shell: python /opt/openbach/frontend_scripts/add_agent.py {{ item }} {{ collector_ip }} {{ agent_username }} {{ agent_password }}
      with_items: '{{agents}}'
      tags:
        - add_agent

    - name: Del an Agent
      shell: python /opt/openbach/frontend_scripts/del_agent.py {{ item }}
      with_items: '{{agents}}'
      tags:
        - del_agent

