# 
#   OpenBACH is a generic testbed able to control/configure multiple
#   network/physical entities (under test) and collect data from them. It is
#   composed of an Auditorium (HMIs), a Controller, a Collector and multiple
#   Agents (one for each network entity that wants to be tested).
#   
#   
#   Copyright © 2016 CNES
#   
#   
#   This file is part of the OpenBACH testbed.
#   
#   
#   OpenBACH is a free software : you can redistribute it and/or modify it under the
#   terms of the GNU General Public License as published by the Free Software
#   Foundation, either version 3 of the License, or (at your option) any later
#   version.
#   
#   This program is distributed in the hope that it will be useful, but WITHOUT
#   ANY WARRANTY, without even the implied warranty of MERCHANTABILITY or FITNESS
#   FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
#   details.
#   
#   You should have received a copy of the GNU General Public License along with
#   this program. If not, see http://www.gnu.org/licenses/.
#   
#   
#   
#   @file     install_synchronization.yml
#   @brief    Playbook that install the Job synchronization
#   @author   Adrien THIBAUD <adrien.thibaud@toulouse.viveris.com>


---

- hosts: Agents
  vars_files:
    - vars/main.yml
  vars:
    - job_conf: synchronization.yml

  tasks:
  - name: Create Synchronization repository
    file: path=/opt/openbach-jobs/synchronization state=directory mode=0755
    become: yes

  - name: Install Synchronization Job
    copy: src=files/{{ item.file }} dest=/opt/openbach-jobs/synchronization/ mode={{ item.mode }}
    with_items:
      - { file: 'synchronization.help', mode: '0644' }
    become: yes
  
  - name: Inform Agent that Synchronization is installed
    template: src=files/{{ job_conf }} dest=/opt/openbach-agent/jobs/{{ job_conf }} mode=0644
    become: yes

  - include: '{{ path_src }}/add_job.yml'

