---

- hosts: Agents
  remote_user: root
  vars_files:
    - vars/main.yml
  vars:
    - job_conf: /opt/openbach-plugins/synchronization/synchronization.cfg

  tasks:
  - name: Create Synchronization repository
    file: path=/opt/openbach-plugins/synchronization state=directory mode=0755

  - name: Install Synchronization
    template: src=templates/synchronization.cfg.j2 dest=/opt/openbach-plugins/synchronization/synchronization.cfg mode=0644

  - include: ../../../roles/agents/tasks/add_job.yml

