---

- name: Add Logstash to boot
  shell: update-rc.d logstash defaults 80

- name: Add ElasticSearch to boot
  shell: update-rc.d elasticsearch defaults 80

- name: Add Collectstats to boot
  shell: update-rc.d collectstats defaults 80

