---

# Install
- include: install_synchro.yml
  tags:
    - install
- include: install_stats.yml
  tags:
    - install
- include: install_logs.yml
  tags:
    - install

# Uninstall
- include: uninstall_synchro.yml
  tags:
    - uninstall
- include: uninstall_stats.yml
  tags:
    - uninstall
- include: uninstall_logs.yml
  tags:
    - uninstall

