---

- name: Create OpenBACH repository
  file: path=/opt/openbach/agent/{{ item }} state=directory
  with_items:
    - jobs
    - job_instances
    - rstats
    - collect_agent
    - openbach_api

- name: Install Rstats
  copy: src=../src/agent/rstats/{{ item }}.py dest=/opt/openbach/agent/rstats/ mode=0755
  with_items:
    - rstats
    - rstats_reload
  notify: restart rstats

- name: Configure Rstats
  template: src=rstats.yml.j2 dest=/opt/openbach/agent/rstats/rstats.yml
  notify: restart rstats

- name: Install Collect Agent
  synchronize: src=../src/agent/collect-agent/ dest=/opt/openbach/agent/collect_agent/ recursive=yes delete=yes
  notify: build collect agent library

- name: Install OpenBACH API
  synchronize: src=../src/agent/openbach-api/ dest=/opt/openbach/agent/openbach_api/ recursive=yes delete=yes rsync_opts=--exclude=*__pycache__/*
  notify: build openbach api packages

- name: Install the Agent's Daemon
  copy: src=../src/agent/openbach-agent/{{ item.name }} dest=/opt/openbach/agent/ mode={{ item.mode }}
  with_items:
    - {name: 'openbach_agent.py', mode: '0755'}
    - {name: 'openbach_agent_filter.conf', mode: '0644'}
  notify: restart openbach agent

- name: Configure the Agent
  template: src={{ item }}.j2 dest=/opt/openbach/agent/{{ item }}
  with_items:
    - agent_name
    - collector.yml
  vars:
    collector_ip: "{{ collector_machine | default('127.0.0.1') }}"
  notify: restart openbach agent

- name: Copy the version file on the Agent
  copy: src=../openbach-version dest=/opt/openbach/agent/version
